# Generated by Django 5.2.5 on 2025-08-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('ADDRESS', models.TextField(blank=True, null=True)),
                ('GEOLOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('RENT_PER_MONTH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PROPERTY_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('AMENITIES', models.TextField(blank=True, null=True)),
                ('AVAILABILITY_START', models.DateField(blank=True, null=True)),
                ('AVAILABILITY_END', models.DateField(blank=True, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PROPERTY_IMAGE', models.FileField(blank=True, null=True, upload_to='property_images')),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RENTER_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('DATE_FROM', models.DateField(blank=True, null=True)),
                ('DATE_TO', models.DateField(blank=True, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=50, null=True)),
                ('PROPERTY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lucidplus_public.propertydb')),
            ],
        ),
    ]
