# Generated by Django 5.2.5 on 2025-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucidplus_public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROLE', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Renter', 'Renter')], max_length=20, null=True)),
                ('FULL_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
