# Generated by Django 5.2.5 on 2025-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucidplus_public', '0002_signupdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Confirmpassword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
