# Generated by Django 5.2.5 on 2025-08-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucidplus_public', '0003_signupdb_confirmpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdb',
            old_name='Confirmpassword',
            new_name='CONFIRMPASSWORD',
        ),
    ]
